import type { Place } from "./types";

// Seed places so the map, filters, and detail surfaces have something to show
// before any place is added. Bangalore-centric (Indiranagar / central). Replace
// freely — these are illustrative, not real ratings.
function iso(d: string) {
  return new Date(d).toISOString();
}

export const SEED_PLACES: Place[] = [
  {
    id: "seed-toit",
    googlePlaceId: null,
    name: "Toit Brewpub",
    address: "298, 100 Feet Rd, Indiranagar, Bengaluru",
    area: "Indiranagar",
    lat: 12.9784,
    lng: 77.6408,
    status: "visited",
    favorite: true,
    neverAgain: false,
    myRating: 4.7,
    googleRating: 4.5,
    myBudgetPerPerson: 1400,
    googlePriceLevel: 3,
    notes: "Get the Toit Weiss + the wood-fired pizza. Go before 7 or it's a wait.",
    tags: [
      { namespace: "type", value: "bar" },
      { namespace: "cuisine", value: "continental" },
      { namespace: "occasion", value: "friends" },
      { namespace: "vibe", value: "lively" },
      { namespace: "practical", value: "groups" },
    ],
    photos: [],
    visits: [
      {
        id: "v-toit-1",
        visitedOn: "2026-05-18",
        whoWith: "Aman, Riya",
        notes: "Weiss + margherita. Rooftop was packed but worth it.",
        rating: 4.7,
        createdAt: iso("2026-05-18"),
      },
    ],
    source: "manual",
    enrichedAt: null,
    createdAt: iso("2026-05-18"),
  },
  {
    id: "seed-bluetokai",
    googlePlaceId: null,
    name: "Blue Tokai Coffee Roasters",
    address: "Indiranagar, Bengaluru",
    area: "Indiranagar",
    lat: 12.9716,
    lng: 77.6411,
    status: "watchlist",
    favorite: false,
    neverAgain: false,
    myRating: null,
    googleRating: 4.4,
    myBudgetPerPerson: null,
    googlePriceLevel: 2,
    notes: "Heard the single-origin pour-overs are great. Good for working mornings.",
    tags: [
      { namespace: "type", value: "café" },
      { namespace: "occasion", value: "solo" },
      { namespace: "vibe", value: "quiet" },
      { namespace: "practical", value: "parking" },
    ],
    photos: [],
    visits: [],
    source: "search",
    enrichedAt: iso("2026-06-20"),
    createdAt: iso("2026-06-20"),
  },
  {
    id: "seed-toscano",
    googlePlaceId: null,
    name: "Toscano",
    address: "UB City, Vittal Mallya Rd, Bengaluru",
    area: "Vittal Mallya Road",
    lat: 12.9719,
    lng: 77.5957,
    status: "watchlist",
    favorite: false,
    neverAgain: false,
    myRating: null,
    googleRating: 4.5,
    myBudgetPerPerson: null,
    googlePriceLevel: 4,
    notes: "Date-night Italian. Book the terrace.",
    tags: [
      { namespace: "type", value: "restaurant" },
      { namespace: "cuisine", value: "italian" },
      { namespace: "occasion", value: "date" },
      { namespace: "vibe", value: "fine-dining" },
      { namespace: "practical", value: "reservation-needed" },
    ],
    photos: [],
    visits: [],
    source: "paste",
    enrichedAt: iso("2026-06-22"),
    createdAt: iso("2026-06-22"),
  },
  {
    id: "seed-permitroom",
    googlePlaceId: null,
    name: "The Permit Room",
    address: "Church Street, Bengaluru",
    area: "Church Street",
    lat: 12.9752,
    lng: 77.6068,
    status: "visited",
    favorite: false,
    neverAgain: false,
    myRating: 4.2,
    googleRating: 4.3,
    myBudgetPerPerson: 900,
    googlePriceLevel: 2,
    notes: "Filter coffee espresso martini is a gimmick but fun. Solid breakfast.",
    tags: [
      { namespace: "type", value: "restaurant" },
      { namespace: "cuisine", value: "south-indian" },
      { namespace: "occasion", value: "friends" },
      { namespace: "vibe", value: "lively" },
    ],
    photos: [],
    visits: [
      {
        id: "v-pr-1",
        visitedOn: "2026-04-02",
        whoWith: "Solo",
        notes: "Brunch. Bisi bele bath arancini, surprisingly good.",
        rating: 4.2,
        createdAt: iso("2026-04-02"),
      },
    ],
    source: "manual",
    enrichedAt: null,
    createdAt: iso("2026-04-02"),
  },
  {
    id: "seed-naru",
    googlePlaceId: null,
    name: "Naru Noodle Bar",
    address: "Sadashivanagar, Bengaluru",
    area: "Sadashivanagar",
    lat: 13.0068,
    lng: 77.5806,
    status: "watchlist",
    favorite: false,
    neverAgain: false,
    myRating: null,
    googleRating: 4.8,
    myBudgetPerPerson: null,
    googlePriceLevel: 3,
    notes: "Tiny ramen counter, books out instantly. Set reminder for slot drops.",
    tags: [
      { namespace: "type", value: "restaurant" },
      { namespace: "cuisine", value: "japanese" },
      { namespace: "occasion", value: "date" },
      { namespace: "vibe", value: "cozy" },
      { namespace: "practical", value: "reservation-needed" },
    ],
    photos: [],
    visits: [],
    source: "search",
    enrichedAt: iso("2026-06-25"),
    createdAt: iso("2026-06-25"),
  },
  {
    id: "seed-dyu",
    googlePlaceId: null,
    name: "Dyu Art Café",
    address: "Koramangala, Bengaluru",
    area: "Koramangala",
    lat: 12.9341,
    lng: 77.6253,
    status: "visited",
    favorite: false,
    neverAgain: true,
    myRating: 2.6,
    googleRating: 4.3,
    myBudgetPerPerson: 700,
    googlePriceLevel: 2,
    notes: "Pretty, but slow service and overpriced for what it is. Wouldn't return.",
    tags: [
      { namespace: "type", value: "café" },
      { namespace: "occasion", value: "date" },
      { namespace: "vibe", value: "instagrammable" },
    ],
    photos: [],
    visits: [
      {
        id: "v-dyu-1",
        visitedOn: "2026-03-15",
        whoWith: "Riya",
        notes: "Waited 40 min for a sandwich. Nice courtyard though.",
        rating: 2.6,
        createdAt: iso("2026-03-15"),
      },
    ],
    source: "manual",
    enrichedAt: null,
    createdAt: iso("2026-03-15"),
  },
];

// Map starts centered on the cluster of seeds (central Bengaluru).
export const DEFAULT_VIEW = { longitude: 77.61, latitude: 12.972, zoom: 12.2 };
